skinparam backgroundColor #EEEBDC
skinparam handwritten true
skinparam defaultFontName "Lucida Handwriting"
center footer <font color=red>Warning:</font> Created for discussion, needs to be validated
